# Use a lightweight Python base image
FROM python:3.10-slim-bookworm

# Set the working directory
WORKDIR /app

# Install git so you can clone your repository
RUN apt-get update && apt-get install -y git

# Clone your repository and install dependencies
RUN git clone https://github.com/maltosee/vaak_dev.git . && \
    pip install --no-cache-dir -r runpod_tts/requirements.txt

# Set the command to start your FastAPI app with Uvicorn
CMD ["uvicorn", "runpod_ws_service:app", "--host", "0.0.0.0", "--port", "8000"]