[project]
name = "sanskrit-vaak-ws"

[build]
dockerfile = "Dockerfile_ws"

[resources]
cpu = 2
memory = 4
storage = 10

[network]
ports = [8000]
http = false
tcp = [8000]

[runtime]
python_path = "/app"

[scaling]
min_workers = 1
max_workers = 3
idle_timeout = 0