[project]
name = "sanskrit-vaak-tts-ws"

[build]
base_image = "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04"
python_version = "3.10"
cuda_version = "11.8"

[resources]
gpu = "RTX_L4"
cpu = 4
memory = 8
storage = 20

[network]
ports = [8000]
http = false
tcp = [8000]

[runtime]
env = [
    "TORCH_DEVICE=cuda",
    "LOG_LEVEL=INFO",
    "MAX_CLIENTS=10"
]
python_path = "/app"
handler = "runpod_ws_service:app"

[scaling]
min_workers = 0
max_workers = 3
idle_timeout = 30
